# backend/schemas/chat.py
import datetime
from typing import Optional
from pydantic import BaseModel, Field, field_validator


class ChatRequest(BaseModel):
    """Pydantic schema validating incoming user chat payloads."""

    message: str = Field(
        ...,
        description="The chat message input.",
        min_length=1,
        max_length=2000
    )
    conversation_id: Optional[str] = Field(
        None,
        description="Optional session tracking identifier."
    )

    @field_validator("message")
    @classmethod
    def message_must_not_be_blank(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Message content cannot be blank or whitespace.")
        return v.strip()


class ChatResponse(BaseModel):
    """Pydantic schema validating outbound chat response payloads."""

    success: bool = Field(..., description="Whether the request succeeded.")
    response: str = Field(..., description="The textual response generated by ULTRON.")
    conversation_id: str = Field(..., description="The unique session or conversation tracking ID.")
    timestamp: str = Field(..., description="ISO 8601 UTC execution timestamp.")
