# core/agent/planner.py
import logging
from typing import List, Dict, Any
from core.agent.task_graph import TaskGraph, TaskNode

# Phase 9B Context Imports
from core.context.memory_manager import memory_manager

logger = logging.getLogger("ultron-api")


class CandidatePlan:
    """Represents an alternative candidate execution plan generated by the reasoning system."""

    def __init__(
        self,
        name: str,
        graph: TaskGraph,
        expected_success: float,
        confidence: float,
        estimated_cost_tokens: int,
        estimated_latency_sec: float,
        risks: List[str],
        required_tools: List[str],
        dependencies: List[str]
    ):
        self.name = name
        self.graph = graph
        self.expected_success = expected_success
        self.confidence = confidence
        self.estimated_cost_tokens = estimated_cost_tokens
        self.estimated_latency_sec = estimated_latency_sec
        self.risks = risks
        self.required_tools = required_tools
        self.dependencies = dependencies


class Planner:
    """Decomposes complex long-horizon goal statements into multiple candidate plans and selects the best one."""

    def generate_candidates(self, goal_description: str) -> List[CandidatePlan]:
        """Generates alternative candidate plans with distinct metrics, tools, and risk assessments."""
        desc_lower = goal_description.lower().strip()
        candidates = []

        if "prepare system and check time" in desc_lower:
            # Candidate 1: Standard Serial Path (Diagnostic -> Time)
            g1 = TaskGraph()
            node_1 = TaskNode("node_001", "Collect system diagnostics", "system.info", "")
            node_2 = TaskNode("node_002", "Determine current time", "system.time", "", dependencies=["node_001"])
            g1.add_node(node_1)
            g1.add_node(node_2)
            c1 = CandidatePlan(
                name="serial_diagnostic_time",
                graph=g1,
                expected_success=0.98,
                confidence=0.95,
                estimated_cost_tokens=1000,
                estimated_latency_sec=0.2,
                risks=["Diagnostic execution delay"],
                required_tools=["system.info", "system.time"],
                dependencies=["node_001"]
            )
            candidates.append(c1)

            # Candidate 2: Parallel Faster Path (Direct Time check)
            g2 = TaskGraph()
            node_time = TaskNode("node_001", "Determine current time directly", "system.time", "")
            g2.add_node(node_time)
            c2 = CandidatePlan(
                name="direct_time_check",
                graph=g2,
                expected_success=0.95,
                confidence=0.90,
                estimated_cost_tokens=500,
                estimated_latency_sec=0.05,
                risks=[],
                required_tools=["system.time"],
                dependencies=[]
            )
            candidates.append(c2)

        elif "open chrome and take a screenshot" in desc_lower:
            # Candidate 1: Safe App Open & Screenshot
            g1 = TaskGraph()
            node_1 = TaskNode("node_001", "Launch Chrome browser", "app.open", "chrome")
            node_2 = TaskNode("node_002", "Capture host screen", "system.screenshot", "", dependencies=["node_001"])
            g1.add_node(node_1)
            g1.add_node(node_2)
            c1 = CandidatePlan(
                name="standard_chrome_screenshot",
                graph=g1,
                expected_success=0.92,
                confidence=0.90,
                estimated_cost_tokens=1500,
                estimated_latency_sec=1.5,
                risks=["App launch fails due to missing executable"],
                required_tools=["app.open", "system.screenshot"],
                dependencies=["node_001"]
            )
            candidates.append(c1)

            # Candidate 2: Web fallback path
            g2 = TaskGraph()
            node_1 = TaskNode("node_001", "Open browserFallback screenshot", "web.search", "google.com")
            g2.add_node(node_1)
            c2 = CandidatePlan(
                name="web_search_screenshot_fallback",
                graph=g2,
                expected_success=0.85,
                confidence=0.80,
                estimated_cost_tokens=1000,
                estimated_latency_sec=2.0,
                risks=["Network latency"],
                required_tools=["web.search"],
                dependencies=[]
            )
            candidates.append(c2)

        elif "shutdown" in desc_lower:
            # Candidate 1: Dangerous system shutdown (HIGH RISK)
            g1 = TaskGraph()
            node_1 = TaskNode("node_001", "Trigger shutdown", "shutdown", "")
            g1.add_node(node_1)
            c1 = CandidatePlan(
                name="danger_shutdown",
                graph=g1,
                expected_success=1.0,
                confidence=0.99,
                estimated_cost_tokens=500,
                estimated_latency_sec=3.0,
                risks=["Loss of session connectivity"],
                required_tools=["shutdown"],
                dependencies=[]
            )
            candidates.append(c1)

        else:
            # Default General Chat Candidate
            g1 = TaskGraph()
            node_1 = TaskNode("node_001", "Process general prompt", "chat", goal_description)
            g1.add_node(node_1)
            c1 = CandidatePlan(
                name="default_chat_opinion",
                graph=g1,
                expected_success=0.99,
                confidence=0.95,
                estimated_cost_tokens=500,
                estimated_latency_sec=0.1,
                risks=[],
                required_tools=["chat"],
                dependencies=[]
            )
            candidates.append(c1)

        return candidates

    def generate_plan(self, goal_description: str) -> TaskGraph:
        """Parse the goal, generate candidate plans, select the best candidate, and return its TaskGraph."""
        logger.info("Generating candidate plans for goal: '%s'", goal_description)

        # 1. Query past strategies from Strategy Memory
        relevant_strats = memory_manager.get_relevant_memories(goal_description, limit=2)
        past_success_boost = 0.0
        for strat in relevant_strats:
            if strat.get("source_partition") == "Strategy":
                # Boost confidence if we have historically succeeded at this exact/similar task pattern
                past_success_boost += 0.05
                logger.info("Phase 9B Planner: Found highly successful historical strategy template. Boosting expectation by 5%%.")

        candidates = self.generate_candidates(goal_description)

        # Integration Hook: Ingest Neural Schema Causal Forecasts as advisory metadata
        try:
            from core.neural.prediction_engine import prediction_engine
            for candidate in candidates:
                risk = prediction_engine.compute_advisory_failure_risk(candidate.name)
                if risk > 0.0:
                    candidate.risks.append(f"Advisory Causal Failure Risk: {risk:.1%}")
        except Exception as e:
            logger.debug("Neural prediction engine query bypassed in Planner: %s", e)

        if not candidates:
            # Fallback safe plan
            logger.warning("No candidate plans generated. Emitting default single-node graph.")
            g = TaskGraph()
            g.add_node(TaskNode("node_001", "Process general prompt", "chat", goal_description))
            return g

        # Select best candidate plan based on expected success (boosted by experience) and cost constraints
        best_candidate = candidates[0]
        # Apply the success boost to all candidate expectation scores based on historical memory
        best_candidate.expected_success = min(1.0, best_candidate.expected_success + past_success_boost)

        for candidate in candidates[1:]:
            candidate.expected_success = min(1.0, candidate.expected_success + past_success_boost)
            # If the candidate has higher expected success, or same success with lower token cost, prioritize it
            if candidate.expected_success > best_candidate.expected_success:
                best_candidate = candidate
            elif candidate.expected_success == best_candidate.expected_success:
                if candidate.estimated_cost_tokens < best_candidate.estimated_cost_tokens:
                    best_candidate = candidate

        logger.info(
            "Selected best candidate plan: '%s' (Expected Success: %.2f, Confidence: %.2f)",
            best_candidate.name,
            best_candidate.expected_success,
            best_candidate.confidence
        )
        return best_candidate.graph


planner = Planner()
